---
- name: Uninstall cron job for endpoint
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure backup directory exists
      file:
        path: /root/gaianet-chat
        state: directory
        mode: '0755'

   - name: Backup the crontab
      shell: |
        timestamp=$(date +"%Y%m%d-%H%M%S")
        crontab -l > /root/gaianet-chat/crontab-backup-${timestamp}.txt
      ignore_errors: true

    - name: Remove all crontab jobs
      cron:
        name: '*'
        state: absent